version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn_rails -c /coffee_app/config/unicorn.conf.rb -D -E production 
#    command: bundle exec unicorn_rails -c /coffee_app/config/unicorn.conf.rb
    ports:
      - '3001:3000'
    volumes:
      - tmp_data:/coffee_app/tmp/sockets
      - .:/coffee_app

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - tmp_data:/var/tmp/

volumes:
  db_data:
  tmp_data: