development:
  adapter: mysql2
  encoding: utf8
  database: coffee_app_development
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: coffee_app_test
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>

production:
  adapter: mysql2
  database: coffee_app_production
  host: <%= ENV['DB_HOSTNAME'] %>
  encoding: utf8
  username: root
  reconnect: false
  pool: 5
  password: <%= ENV['DB_PASSWORD'] %>
