default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: coffee_app_development

test:
  <<: *default
  database: coffee_app_test

production:
  <<: *default
  database: coffee_app_production